# Generated by Django 5.0 on 2025-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
