# Generated by Django 5.0 on 2025-02-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchatapp', '0002_alter_login_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
